#!/usr/bin/python

#######################################################################
# This file is part of steve.
#
# Copyright (C) 2012, 2013 Will Kahn-Greene
# Licensed under the Simplified BSD License. See LICENSE for full
# license.
#######################################################################

"""
This is the command-line side of steve
"""

import sys
import os


try:
    import steve.cmdline
except ImportError:
    sys.stderr.write(
        'The steve library is not on your sys.path.  Please install steve.\n')
    sys.exit(1)


if __name__ == '__main__':
    sys.exit(steve.cmdline.main(sys.argv[1:]))
